[package]
name = "asset-catalog"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
asset-core = { path = "../asset-core" }
asset-index = { path = "../index" }
metadata = { path = "../metadata" }
serde.workspace = true
thiserror.workspace = true
uuid.workspace = true

[dev-dependencies]
asset-filesystem = { path = "../filesystem" }
tempfile.workspace = true

[lints]
workspace = true
