[package]
name = "asset-selection"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
asset-catalog = { path = "../catalog" }
asset-index = { path = "../index" }
chrono.workspace = true
serde.workspace = true
thiserror.workspace = true
uuid.workspace = true

[dev-dependencies]
asset-core = { path = "../asset-core" }

[lints]
workspace = true
