[package]
name = "asset-filesystem"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
asset-core = { path = "../asset-core" }
metadata = { path = "../metadata" }
globset.workspace = true
imagesize.workspace = true
infer.workspace = true
kamadak-exif.workspace = true
notify.workspace = true
resource-control = { path = "../resource-control" }
serde.workspace = true
serde_yaml_ng.workspace = true
tempfile.workspace = true
thiserror.workspace = true
uuid.workspace = true
unicode-normalization.workspace = true
walkdir.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
