[package]
name = "material-eagle-desktop"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
name = "material_eagle_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build.workspace = true

[dependencies]
app-config = { path = "../../../crates/app-config" }
asset-catalog = { path = "../../../crates/catalog" }
asset-core = { path = "../../../crates/asset-core" }
asset-filesystem = { path = "../../../crates/filesystem" }
asset-index = { path = "../../../crates/index" }
asset-link-resolver = { path = "../../../crates/link-resolver" }
asset-preview = { path = "../../../crates/preview" }
asset-transactions = { path = "../../../crates/transactions" }
metadata = { path = "../../../crates/metadata" }
resource-control = { path = "../../../crates/resource-control" }
serde.workspace = true
sha2.workspace = true
tauri.workspace = true
tauri-plugin-clipboard-manager = "=2.3.2"
uuid.workspace = true

[features]
custom-protocol = ["tauri/custom-protocol"]

[dev-dependencies]
serde_json.workspace = true
tempfile.workspace = true

[lints]
workspace = true
