[package]
name = "asset-index"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
asset-core = { path = "../asset-core" }
chrono.workspace = true
serde.workspace = true
thiserror.workspace = true
unicode-normalization.workspace = true
uuid.workspace = true

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
