[package]
name = "asset-tag-renames"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
fault-injection = ["asset-transactions/fault-injection"]

[dependencies]
asset-saved-filters = { path = "../saved-filters" }
asset-transactions = { path = "../transactions" }
chrono.workspace = true
metadata = { path = "../metadata" }
serde.workspace = true
serde_yaml_ng.workspace = true
tempfile.workspace = true
thiserror.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
