[package]
name = "asset-saved-filters"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
asset-core = { path = "../asset-core" }
asset-index = { path = "../index" }
chrono.workspace = true
serde.workspace = true
serde_yaml_ng.workspace = true
sha2.workspace = true
tempfile.workspace = true
thiserror.workspace = true
unicode-casefold.workspace = true
unicode-normalization.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
