[package]
name = "asset-preview"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
asset-core = { path = "../asset-core" }
image.workspace = true
resource-control = { path = "../resource-control" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tempfile.workspace = true
thiserror.workspace = true
uuid.workspace = true

[dev-dependencies]
metadata = { path = "../metadata" }

[features]
fault-injection = []

[lints]
workspace = true
